[changelog]
# Enable verbose logging and include all commits
filter = false
sort_commits = "oldest"

[git]
# Disable strict conventional commit parsing
conventional_commits = false
filter_unconventional = false
split_commits = false

# Explicit commit parsers
[[changelog.commit_parsers]]
pattern = "^feat"
group = "Features"

[[changelog.commit_parsers]]
pattern = "^fix"
group = "Bug Fixes"

[[changelog.commit_parsers]]
pattern = ".*"
group = "Other Changes"

[changelog.template]
body = """
{% if version %}## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% endif %}
{% for group, commits in groups %}### {{ group | trim | upper_first }}
{% for commit in commits %}
- Commit: `{{ commit.id }}` 
  Message: {{ commit.message | trim | upper_first }}
  Date: {{ commit.date }}
{% endfor %}
{% endfor %}
"""

# Additional settings to ensure comprehensive parsing
[changelog.sort]
order = "reverse"