[changelog]
# Disable strict filtering
filter = false

[git]
# More flexible commit parsing
conventional_commits = false
filter_unconventional = false
split_commits = false
# Allow parsing of various commit message formats
commit_parsers = [
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^docs", group = "Documentation" },
    { message = "^perf", group = "Performance" },
    { message = "^refactor", group = "Refactoring" },
    { message = "^test", group = "Testing" },
    { message = "^chore", group = "Maintenance Tasks" },
    # Catch-all for commits that don't match typical patterns
    { message = ".*", group = "Other Changes" }
]

[changelog.template]
body = """
{% if version %}## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% endif %}
{% for group, commits in groups %}### {{ group | striptags | trim | upper_first }}
{% for commit in commits %}
- `{{ commit.id | truncate(length=7, end="") }}` {{ commit.message | upper_first }}{% endfor %}
{% endfor %}
"""