[changelog]
# Capture all commits
filter = false

[git]
# Most permissive parsing
conventional_commits = false
filter_unconventional = false
split_commits = false

[changelog.template]
body = """
{% for commit in commits %}
- {{ commit.id }}: {{ commit.message }}
{% endfor %}
"""