name: Changelog Generator

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install git-cliff
        run: |
          # Download the latest release
          curl -LO https://github.com/orhun/git-cliff/releases/latest/download/git-cliff-linux-x86_64.tar.gz

          # Extract the archive
          tar -xzf git-cliff-linux-x86_64.tar.gz

          # Make the binary executable
          chmod +x git-cliff

          # Move to a directory in PATH
          sudo mv git-cliff /usr/local/bin/

          # Verify installation
          git-cliff --version

      - name: Generate Changelog
        run: |
          # Generate changelog using default or custom configuration
          git-cliff -o CHANGELOG.md

      - name: Display Changelog
        run: |
          echo "Generated Changelog:"
          cat CHANGELOG.md

      - name: Commit Changelog
        uses: EndBug/add-and-commit@v9
        with:
          add: "CHANGELOG.md"
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "Update CHANGELOG.md"

      - name: Create Release Changelog
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_file: CHANGELOG.md
