name: Generate Changelog

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Git Logs
        run: |
          echo "Total commits:"
          git rev-list --count HEAD
          echo "\nLast 10 commits:"
          git log -n 10 --pretty=format:"%h - %s"

      - name: Generate Changelog
        uses: orhun/git-cliff-action@v2
        with:
          config: cliff.toml
          args: -vv
        env:
          OUTPUT: CHANGELOG.md

      - name: Display Changelog
        run: |
          echo "Generated Changelog:"
          cat CHANGELOG.md

      - name: Archive Changelog
        uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: CHANGELOG.md
