name: Changelog Generator

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Changelog
        uses: ardalanamini/auto-changelog@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-name: Latest
          mentions: true
          breaking-changes: true
