name: Generate Changelog

on:
  push:
    tags:
      - "v*" # Trigger on version tags (e.g., v1.0.0)

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install -g conventional-changelog-cli

      - name: Generate Changelog
        run: conventional-changelog -p angular -i CHANGELOG.md -s

      - name: Debugging
        run: git rev-parse --abbrev-ref HEAD

      - name: Commit and Push Changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Marcio Maisonette"
          git config user.email "marciomaisonette@gmail.com"
          git add CHANGELOG.md
          git commit -m "chore: update changelog [skip ci]"

          git push origin $(git rev-parse --abbrev-ref HEAD)
